version: "3.8"
services:
    postgres:
        image: sdc-postgres
        container_name: sdc-postgres
        ports:
            - 3001:5432
        environment: 
            SEQ_DB: sdc
            SEQ_USER: postgres
            SEQ_PW: password
            DATABASE_URL: postgres://postgres:password@sdc-postgres:5432/sdc
        build:
          context: .
          dockerfile: postgres.Dockerfile 
    node:
            image: sdc-node
            container_name: sdc-node
            depends_on:
                - postgres
            ports: 
                - 3002:3000
            build:
                context: .
                dockerfile: node.Dockerfile