version: "3.8"
services:
    frontend:
        image: sdc-m-frontend
        container_name: sdc-m-frontend
        ports:
            - 3002:3500
        build:
            context: ./frontend
            dockerfile: frontend.Dockerfile
        restart: on-failure
    postgres:
        image: sdc-m-postgres
        container_name: sdc-m-postgres
        ports:
            - 3001:5432
        environment: 
            SEQ_DB: sdc
            SEQ_USER: postgres
            SEQ_PW: password
            DATABASE_URL: postgres://postgres:password@sdc-m-postgres:5432/sdc
        build:
          context: ./db
          dockerfile: postgres.Dockerfile 
        
    node:
            image: sdc-m-node
            container_name: sdc-m-node
            depends_on:
                - postgres
            ports: 
                - 3000:3000
            build:
                context: ./server
                dockerfile: node.Dockerfile
            restart: on-failure