version: "3.3"
services:
    postgres:
        image: sdc-postgres
        container_name: sdc-postgres
        ports:
            - 3001:5432
        environment: 
            POSTGRES_HOST_AUTH_METHOD: "trust"
        build:
          context: .
          dockerfile: postgres.Dockerfile 
    node:
            image: sdc-node
            container_name: sdc-node
            depends_on:
                - postgres
            ports: 
                - 3000:3000
            build:
                context: .
                dockerfile: node.Dockerfile
    nginx:
        image: sdc-ngnix
        container_name: sdc-ngnix
        restart: always 
        build:
            dockerfile: nginx.Dockerfile
            context: .
        ports:
            - '80:80'